export interface CountryOption {
    code: string;
    name: string;
    flag: string;
    display: string;
}

export const COUNTRIES: CountryOption[] = [
    { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', display: '🇦🇫 Afghanistan' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', display: '🇦🇱 Albania' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', display: '🇩🇿 Algeria' },
  { code: 'AS', name: 'American Samoa', flag: '🇦🇸', display: '🇦🇸 American Samoa' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩', display: '🇦🇩 Andorra' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', display: '🇦🇴 Angola' },
  { code: 'AI', name: 'Anguilla', flag: '🇦🇮', display: '🇦🇮 Anguilla' },
  { code: 'AQ', name: 'Antarctica', flag: '🇦🇶', display: '🇦🇶 Antarctica' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', display: '🇦🇬 Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', display: '🇦🇷 Argentina' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', display: '🇦🇲 Armenia' },
  { code: 'AW', name: 'Aruba', flag: '🇦🇼', display: '🇦🇼 Aruba' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', display: '🇦🇺 Australia' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', display: '🇦🇹 Austria' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', display: '🇦🇿 Azerbaijan' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', display: '🇧🇸 Bahamas' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', display: '🇧🇭 Bahrain' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', display: '🇧🇩 Bangladesh' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧', display: '🇧🇧 Barbados' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾', display: '🇧🇾 Belarus' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', display: '🇧🇪 Belgium' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', display: '🇧🇿 Belize' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', display: '🇧🇯 Benin' },
  { code: 'BM', name: 'Bermuda', flag: '🇧🇲', display: '🇧🇲 Bermuda' },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹', display: '🇧🇹 Bhutan' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', display: '🇧🇴 Bolivia' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', flag: '🇧🇶', display: '🇧🇶 Bonaire, Sint Eustatius and Saba' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', display: '🇧🇦 Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', display: '🇧🇼 Botswana' },
  { code: 'BV', name: 'Bouvet Island', flag: '🇧🇻', display: '🇧🇻 Bouvet Island' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', display: '🇧🇷 Brazil' },
  { code: 'IO', name: 'British Indian Ocean Territory', flag: '🇮🇴', display: '🇮🇴 British Indian Ocean Territory' },
  { code: 'BN', name: 'Brunei Darussalam', flag: '🇧🇳', display: '🇧🇳 Brunei Darussalam' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', display: '🇧🇬 Bulgaria' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', display: '🇧🇫 Burkina Faso' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', display: '🇧🇮 Burundi' },
  { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻', display: '🇨🇻 Cabo Verde' },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', display: '🇰🇭 Cambodia' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', display: '🇨🇲 Cameroon' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', display: '🇨🇦 Canada' },
  { code: 'KY', name: 'Cayman Islands', flag: '🇰🇾', display: '🇰🇾 Cayman Islands' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', display: '🇨🇫 Central African Republic' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', display: '🇹🇩 Chad' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', display: '🇨🇱 Chile' },
  { code: 'CN', name: 'China', flag: '🇨🇳', display: '🇨🇳 China' },
  { code: 'CX', name: 'Christmas Island', flag: '🇨🇽', display: '🇨🇽 Christmas Island' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', flag: '🇨🇨', display: '🇨🇨 Cocos (Keeling) Islands' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', display: '🇨🇴 Colombia' },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', display: '🇰🇲 Comoros' },
  { code: 'CD', name: 'Congo (Democratic Republic)', flag: '🇨🇩', display: '🇨🇩 Congo (Democratic Republic)' },
  { code: 'CG', name: 'Congo (Republic)', flag: '🇨🇬', display: '🇨🇬 Congo (Republic)' },
  { code: 'CK', name: 'Cook Islands', flag: '🇨🇰', display: '🇨🇰 Cook Islands' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', display: '🇨🇷 Costa Rica' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', display: '🇭🇷 Croatia' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', display: '🇨🇺 Cuba' },
  { code: 'CW', name: 'Curaçao', flag: '🇨🇼', display: '🇨🇼 Curaçao' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', display: '🇨🇾 Cyprus' },
  { code: 'CZ', name: 'Czechia', flag: '🇨🇿', display: '🇨🇿 Czechia' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮', display: '🇨🇮 Côte d\'Ivoire' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', display: '🇩🇰 Denmark' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', display: '🇩🇯 Djibouti' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲', display: '🇩🇲 Dominica' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', display: '🇩🇴 Dominican Republic' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', display: '🇪🇨 Ecuador' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', display: '🇪🇬 Egypt' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', display: '🇸🇻 El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', display: '🇬🇶 Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷', display: '🇪🇷 Eritrea' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', display: '🇪🇪 Estonia' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', display: '🇸🇿 Eswatini' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', display: '🇪🇹 Ethiopia' },
  { code: 'FK', name: 'Falkland Islands', flag: '🇫🇰', display: '🇫🇰 Falkland Islands' },
  { code: 'FO', name: 'Faroe Islands', flag: '🇫🇴', display: '🇫🇴 Faroe Islands' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', display: '🇫🇯 Fiji' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', display: '🇫🇮 Finland' },
  { code: 'FR', name: 'France', flag: '🇫🇷', display: '🇫🇷 France' },
  { code: 'GF', name: 'French Guiana', flag: '🇬🇫', display: '🇬🇫 French Guiana' },
  { code: 'PF', name: 'French Polynesia', flag: '🇵🇫', display: '🇵🇫 French Polynesia' },
  { code: 'TF', name: 'French Southern Territories', flag: '🇹🇫', display: '🇹🇫 French Southern Territories' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', display: '🇬🇦 Gabon' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲', display: '🇬🇲 Gambia' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪', display: '🇬🇪 Georgia' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', display: '🇩🇪 Germany' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', display: '🇬🇭 Ghana' },
  { code: 'GI', name: 'Gibraltar', flag: '🇬🇮', display: '🇬🇮 Gibraltar' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', display: '🇬🇷 Greece' },
  { code: 'GL', name: 'Greenland', flag: '🇬🇱', display: '🇬🇱 Greenland' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩', display: '🇬🇩 Grenada' },
  { code: 'GP', name: 'Guadeloupe', flag: '🇬🇵', display: '🇬🇵 Guadeloupe' },
  { code: 'GU', name: 'Guam', flag: '🇬🇺', display: '🇬🇺 Guam' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', display: '🇬🇹 Guatemala' },
  { code: 'GG', name: 'Guernsey', flag: '🇬🇬', display: '🇬🇬 Guernsey' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳', display: '🇬🇳 Guinea' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', display: '🇬🇼 Guinea-Bissau' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', display: '🇬🇾 Guyana' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹', display: '🇭🇹 Haiti' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', flag: '🇭🇲', display: '🇭🇲 Heard Island and McDonald Islands' },
  { code: 'VA', name: 'Holy See', flag: '🇻🇦', display: '🇻🇦 Holy See' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', display: '🇭🇳 Honduras' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', display: '🇭🇰 Hong Kong' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', display: '🇭🇺 Hungary' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', display: '🇮🇸 Iceland' },
  { code: 'IN', name: 'India', flag: '🇮🇳', display: '🇮🇳 India' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', display: '🇮🇩 Indonesia' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', display: '🇮🇷 Iran' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', display: '🇮🇶 Iraq' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', display: '🇮🇪 Ireland' },
  { code: 'IM', name: 'Isle of Man', flag: '🇮🇲', display: '🇮🇲 Isle of Man' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', display: '🇮🇱 Israel' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', display: '🇮🇹 Italy' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', display: '🇯🇲 Jamaica' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', display: '🇯🇵 Japan' },
  { code: 'JE', name: 'Jersey', flag: '🇯🇪', display: '🇯🇪 Jersey' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', display: '🇯🇴 Jordan' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', display: '🇰🇿 Kazakhstan' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', display: '🇰🇪 Kenya' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', display: '🇰🇮 Kiribati' },
  { code: 'KP', name: 'Korea (North)', flag: '🇰🇵', display: '🇰🇵 Korea (North)' },
  { code: 'KR', name: 'Korea (South)', flag: '🇰🇷', display: '🇰🇷 Korea (South)' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', display: '🇰🇼 Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', display: '🇰🇬 Kyrgyzstan' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', display: '🇱🇦 Laos' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', display: '🇱🇻 Latvia' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', display: '🇱🇧 Lebanon' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', display: '🇱🇸 Lesotho' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', display: '🇱🇷 Liberia' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', display: '🇱🇾 Libya' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', display: '🇱🇮 Liechtenstein' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', display: '🇱🇹 Lithuania' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', display: '🇱🇺 Luxembourg' },
  { code: 'MO', name: 'Macao', flag: '🇲🇴', display: '🇲🇴 Macao' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', display: '🇲🇬 Madagascar' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', display: '🇲🇼 Malawi' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', display: '🇲🇾 Malaysia' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', display: '🇲🇻 Maldives' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', display: '🇲🇱 Mali' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', display: '🇲🇹 Malta' },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', display: '🇲🇭 Marshall Islands' },
  { code: 'MQ', name: 'Martinique', flag: '🇲🇶', display: '🇲🇶 Martinique' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷', display: '🇲🇷 Mauritania' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺', display: '🇲🇺 Mauritius' },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹', display: '🇾🇹 Mayotte' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', display: '🇲🇽 Mexico' },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲', display: '🇫🇲 Micronesia' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', display: '🇲🇩 Moldova' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', display: '🇲🇨 Monaco' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳', display: '🇲🇳 Mongolia' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪', display: '🇲🇪 Montenegro' },
  { code: 'MS', name: 'Montserrat', flag: '🇲🇸', display: '🇲🇸 Montserrat' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', display: '🇲🇦 Morocco' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', display: '🇲🇿 Mozambique' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', display: '🇲🇲 Myanmar' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦', display: '🇳🇦 Namibia' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', display: '🇳🇷 Nauru' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', display: '🇳🇵 Nepal' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', display: '🇳🇱 Netherlands' },
  { code: 'NC', name: 'New Caledonia', flag: '🇳🇨', display: '🇳🇨 New Caledonia' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', display: '🇳🇿 New Zealand' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', display: '🇳🇮 Nicaragua' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', display: '🇳🇪 Niger' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', display: '🇳🇬 Nigeria' },
  { code: 'NU', name: 'Niue', flag: '🇳🇺', display: '🇳🇺 Niue' },
  { code: 'NF', name: 'Norfolk Island', flag: '🇳🇫', display: '🇳🇫 Norfolk Island' },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', display: '🇲🇰 North Macedonia' },
  { code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵', display: '🇲🇵 Northern Mariana Islands' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', display: '🇳🇴 Norway' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', display: '🇴🇲 Oman' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', display: '🇵🇰 Pakistan' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼', display: '🇵🇼 Palau' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', display: '🇵🇸 Palestine' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', display: '🇵🇦 Panama' },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', display: '🇵🇬 Papua New Guinea' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', display: '🇵🇾 Paraguay' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', display: '🇵🇪 Peru' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', display: '🇵🇭 Philippines' },
  { code: 'PN', name: 'Pitcairn', flag: '🇵🇳', display: '🇵🇳 Pitcairn' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', display: '🇵🇱 Poland' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', display: '🇵🇹 Portugal' },
  { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷', display: '🇵🇷 Puerto Rico' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', display: '🇶🇦 Qatar' },
  { code: 'RE', name: 'Réunion', flag: '🇷🇪', display: '🇷🇪 Réunion' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', display: '🇷🇴 Romania' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', display: '🇷🇺 Russia' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', display: '🇷🇼 Rwanda' },
  { code: 'BL', name: 'Saint Barthélemy', flag: '🇧🇱', display: '🇧🇱 Saint Barthélemy' },
  { code: 'SH', name: 'Saint Helena', flag: '🇸🇭', display: '🇸🇭 Saint Helena' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', display: '🇰🇳 Saint Kitts and Nevis' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', display: '🇱🇨 Saint Lucia' },
  { code: 'MF', name: 'Saint Martin', flag: '🇲🇫', display: '🇲🇫 Saint Martin' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', flag: '🇵🇲', display: '🇵🇲 Saint Pierre and Miquelon' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', display: '🇻🇨 Saint Vincent and the Grenadines' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', display: '🇼🇸 Samoa' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲', display: '🇸🇲 San Marino' },
  { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', display: '🇸🇹 Sao Tome and Principe' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', display: '🇸🇦 Saudi Arabia' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', display: '🇸🇳 Senegal' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', display: '🇷🇸 Serbia' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', display: '🇸🇨 Seychelles' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', display: '🇸🇱 Sierra Leone' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', display: '🇸🇬 Singapore' },
  { code: 'SX', name: 'Sint Maarten', flag: '🇸🇽', display: '🇸🇽 Sint Maarten' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', display: '🇸🇰 Slovakia' },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮', display: '🇸🇮 Slovenia' },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', display: '🇸🇧 Solomon Islands' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴', display: '🇸🇴 Somalia' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', display: '🇿🇦 South Africa' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', flag: '🇬🇸', display: '🇬🇸 South Georgia and the South Sandwich Islands' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸', display: '🇸🇸 South Sudan' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', display: '🇪🇸 Spain' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', display: '🇱🇰 Sri Lanka' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', display: '🇸🇩 Sudan' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', display: '🇸🇷 Suriname' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', flag: '🇸🇯', display: '🇸🇯 Svalbard and Jan Mayen' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', display: '🇸🇪 Sweden' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', display: '🇨🇭 Switzerland' },
  { code: 'SY', name: 'Syria', flag: '🇸🇾', display: '🇸🇾 Syria' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', display: '🇹🇼 Taiwan' },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', display: '🇹🇯 Tajikistan' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', display: '🇹🇿 Tanzania' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', display: '🇹🇭 Thailand' },
  { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱', display: '🇹🇱 Timor-Leste' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', display: '🇹🇬 Togo' },
  { code: 'TK', name: 'Tokelau', flag: '🇹🇰', display: '🇹🇰 Tokelau' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', display: '🇹🇴 Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', display: '🇹🇹 Trinidad and Tobago' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', display: '🇹🇳 Tunisia' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', display: '🇹🇷 Turkey' },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', display: '🇹🇲 Turkmenistan' },
  { code: 'TC', name: 'Turks and Caicos Islands', flag: '🇹🇨', display: '🇹🇨 Turks and Caicos Islands' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', display: '🇹🇻 Tuvalu' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', display: '🇺🇬 Uganda' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', display: '🇺🇦 Ukraine' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', display: '🇦🇪 United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', display: '🇬🇧 United Kingdom' },
  { code: 'US', name: 'United States', flag: '🇺🇸', display: '🇺🇸 United States' },
  { code: 'UM', name: 'United States Minor Outlying Islands', flag: '🇺🇲', display: '🇺🇲 United States Minor Outlying Islands' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', display: '🇺🇾 Uruguay' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', display: '🇺🇿 Uzbekistan' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', display: '🇻🇺 Vanuatu' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', display: '🇻🇪 Venezuela' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', display: '🇻🇳 Vietnam' },
  { code: 'VG', name: 'Virgin Islands (British)', flag: '🇻🇬', display: '🇻🇬 Virgin Islands (British)' },
  { code: 'VI', name: 'Virgin Islands (U.S.)', flag: '🇻🇮', display: '🇻🇮 Virgin Islands (U.S.)' },
  { code: 'WF', name: 'Wallis and Futuna', flag: '🇼🇫', display: '🇼🇫 Wallis and Futuna' },
  { code: 'EH', name: 'Western Sahara', flag: '🇪🇭', display: '🇪🇭 Western Sahara' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪', display: '🇾🇪 Yemen' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', display: '🇿🇲 Zambia' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', display: '🇿🇼 Zimbabwe' },
  { code: 'ZZ', name: 'Unknown', flag: '🏳️', display: '🏳️ Unknown' }
];